spring:
  application:
    name: gateway-server
  main:
    allow-bean-definition-overriding: true

server:
  port: 51210

eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
  server:
    enable-self-preservation: false    #关闭服务器自我保护，客户端心跳检测15分钟内错误达到80%服务会保护，导致别人还认为是好用的服务
    eviction-interval-timer-in-ms: 10000 #清理间隔（单位毫秒，默认是60*1000）5秒将客户端剔除的服务在服务注册列表中剔除#
    shouldUseReadOnlyResponseCache: true #eureka是CAP理论种基于AP策略，为了保证强一致性关闭此切换CP 默认不关闭 false关闭
  client:
    register-with-eureka: true  #false:不作为一个客户端注册到注册中心
    fetch-registry: true      #为true时，可以启动，但报异常：Cannot execute request on any known server
    instance-info-replication-interval-seconds: 10
    service-url:
      defaultZone: http://localhost:51200/eureka/

#register-with-eureka: false #自己就是注册中心，不用注册自己
#fetch-registry: false  #要不要去注册中心获取其他服务的地址


zuul:
  routes:
    certificate:
      stripPrefix: false
      serviceId: certificate-server
      path: /certificate/**
    resource:
      stripPrefix: false
      serviceId: resource-server
      path: /resource/**
  retryable: true
  ignored-services: '*'
  add-host-header: true
  sensitive-headers: '*'


feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true